config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  scope "/:locale", locale: /#{I18n.available_locales.join('|')}/ do
    namespace :admin do 
      resources :areas, param: :slug do
        resources :problems, only: :index
      end
      resources :problems, except: :index
      resources :boulders
      resources :sectors
      resources :imports do
        get 'apply', on: :member
      end
      resources :topos
      resources :problem_imports
      resources :bleau_problems
      resources :lines
      resources :pois
      resources :poi_routes
      resources :contribution_requests
      resources :contributions
      resources :audits
      resources :redirects, only: :new

      get "contribute", to: "contribute#dashboard"

      root 'areas#index'
    end

    scope "articles" do
      scope "beginners-guide" do
        get '/', to: "articles#beginners_guide", as: :beginners_guide
        get 'equipment', to: "articles#equipment", as: :equipment
        get 'choose-area', to: "articles#choose_area", as: :choose_area
        get 'choose-problems', to: "articles#choose_problems", as: :choose_problems
        get 'climb-safely', to: "articles#climb_safely", as: :climb_safely
        get 'rules', to: "articles#rules", as: :rules
      end
      scope "top-areas" do
        get '/', to: redirect("/%{locale}/wicklow")
        get 'level', to: redirect("/%{locale}/wicklow"), as: :legacy_top_areas_level # keep until end of 2023
        get 'groups', to: redirect("/%{locale}/wicklow"), as: :legacy_top_areas_groups # keep until end of 2023
        get 'beginner', to: redirect("/%{locale}/articles/beginners-guide/choose-area"), as: :legacy_top_areas_beginner # keep until end of 2023
        get 'train', to: "articles#top_areas_train", as: :top_areas_train
        get 'dry_fast', to: "articles#top_areas_dry_fast", as: :top_areas_dry_fast
      end
      root to: redirect("/%{locale}/articles/beginners-guide"), as: :articles
    end

    resources :reports

    namespace :mapping do
      resources :problems, only: [:show, :index]
      resources :contributions, only: [:show, :new, :create]
      resources :requests, controller: "contribution_requests", only: [:index]
      get 'map(/:slug)', to: '/map#index', as: :map, defaults: { contribute: true }
      get "/", to: "areas#index"
    end
    get "contribute/map", to: redirect('/%{locale}/mapping/map'), as: :map_contribute_legacy_redirect # can be removed as soon as 2024-01-01

    scope 'wicklow' do
      resources :sectors, only: [:show, :index]
      resources :problems, only: [:index]

      get "/levels", to: "areas#levels", as: :areas_levels

      get "/areas", to: redirect("/%{locale}/wicklow"), as: :areas_legacy # keep until ??

      get ":slug/:id", to: "problems#show", as: :area_problem, id: /\d.*/
      get ":slug/map", to: redirect('/%{locale}/map/%{slug}'), as: :map_area_legacy_redirect # keep until end of 2023
      get ":slug/problems", to: "areas#problems", as: :area_problems
      get ":slug", to: "areas#show", as: :area

      get "/", to: "areas#index", as: :areas
    end

    get 'map(/:slug)', to: 'map#index', as: :map
    get 'app', to: 'pages#app', as: :app
    get 'privacy', to: 'pages#privacy', as: :privacy
    get 'about', to: 'pages#about', as: :about
    get 'contribute', to: 'pages#contribute', as: :contribute
    get 'sector7a', to: 'sector7a#index', as: :sector7a
    get 'sector7a/problems', to: 'sector7a#problems', as: :sector7a_problems
    get 'sector7a/map', to: 'map#index', as: :sector7a_map, defaults: { sector7a: true }

    resources :redirects, only: :new # useful for redirects where we only know the problem_id or area_id, eg. mapbox

    # Permalinks (don't remove!)
    get '/p/:id', to: "welcome#problem_permalink" # used by the apps to redirect to a problem webpage
  end

  namespace :api do
    namespace :v1 do
      resources :topos, only: :show
      resources :areas do
        resources :topos, only: :index
        get "map", to: "maps#show", as: :area_map
      end
    end
  end

  get "search", to: "search#search", as: :search
  get '/:locale', to: 'welcome#index', locale: /#{I18n.available_locales.join('|')}/, as: :root_localized
  root to: 'welcome#root'

  mount Sidekiq::Web => "/sidekiqq"

  # =============
  # Proxy routes 
  # =============
  # Use proxy mode (=streaming) instead of redirects to allow CDNs to easily cache our assets
  # inspired by https://edgeguides.rubyonrails.org/active_storage_overview.html#putting-a-cdn-in-front-of-active-storage
  # more info: https://github.com/rails/rails/tree/main/activestorage/app/controllers

  # Guessable urls (used by the mobile apps)
  get '/proxy/topos/:id', to: "proxy#show", as: :topo_proxy

  # General solution
  direct :cdn_image do |model, options|
    expires_in = options.delete(:expires_in) { ActiveStorage.urls_expire_in }
    options = options.merge(host: Rails.application.config.asset_host) unless Rails.env.local?

    if model.respond_to?(:signed_id)
      route_for(
        :rails_service_blob_proxy,
        model.signed_id(expires_in: expires_in),
        model.filename,
        options
      )
    else
      signed_blob_id = model.blob.signed_id(expires_in: expires_in)
      variation_key  = model.variation.key
      filename       = model.blob.filename

      route_for(
        :rails_blob_representation_proxy,
        signed_blob_id,
        variation_key,
        filename,
        options
      )
    end
  end
end

app/models/poi.rb
class Poi < ApplicationRecord
  has_many :poi_routes
  has_many :areas

  audited

  TYPE_VALUES = %w(parking train_station)

  validates :poi_type, inclusion: { in: TYPE_VALUES }

  scope :train_station, -> { where(poi_type: "train_station") }
  scope :parking, -> { where(poi_type: "parking") }

  def parking?
    poi_type.to_s == "parking"
  end

  def train_station?
    poi_type.to_s == "train_station"
  end
end

app/controllers/admin/pois_controller.rb
class Admin::PoisController < Admin::BaseController
  def index
    @pois = Poi.order(:id)
  end

  def new
    @poi = Poi.new
  end

  def create
    poi = Poi.create!(poi_params)

    flash[:notice] = "Poi created"
    redirect_to admin_pois_path
  end

  def edit
    set_poi
  end

  def update
    set_poi

    if @poi.update(poi_params)
      flash[:notice] = "Poi updated"
      redirect_to admin_pois_path
    else
      flash[:error] = @poi.errors.full_messages.join('; ')
      render "edit", status: :unprocessable_entity
    end
  end

  private 
  def poi_params
    params.require(:poi).
      permit(:name, :short_name, :poi_type, :google_url)
  end

  def set_poi
    @poi = Poi.find(params[:id])
  end
end

app/views/admin/pois/_form.html.erb
<div class="col-span-6 sm:col-span-4">
  <%= form.label :name %>
  <%= form.text_field :name, autocomplete: "off" %>
</div>
<div class="col-span-6 sm:col-span-2"></div>

<div class="col-span-6 sm:col-span-4">
  <%= form.label :short_name %>
  <%= form.text_field :short_name, autocomplete: "off" %>
</div>
<div class="col-span-6 sm:col-span-2"></div>

<div class="col-span-6 sm:col-span-3">
  <%= form.label :poi_type %>
  <%= form.select :poi_type, Poi::TYPE_VALUES %>
</div>
<div class="col-span-6 sm:col-span-3"></div>

<div class="col-span-6 sm:col-span-6">
  <%= form.label :google_url %>
  <%= form.text_field :google_url, autocomplete: "off" %>
</div>

app/views/admin/pois/edit.html.erb
<% add_breadcrumb "Pois", admin_pois_path %>
<% add_breadcrumb "Poi ##{@poi.id}", nil, class: "active" %>

<div class="mt-10 sm:mt-0">
  <div class="md:grid md:grid-cols-4 md:gap-6">
    <div class="mt-5 md:mt-0 md:col-span-2">
      <%= form_with model: [:admin, @poi] do |form| %>
        <div class="shadow overflow-hidden sm:rounded-md">
          <div class="px-4 py-5 bg-white sm:p-6">
            <div class="grid grid-cols-6 gap-6">
              <%= render "form", form: form %>
            </div>
          </div>

          <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
            <button type="submit" class="btn">Update</button>
          </div>
        </div>
      <% end %>
    </div>

    <div class="md:col-span-2">
      <div class="px-4 sm:px-0"></div>
    </div>
  </div>
</div>

app/views/admin/pois/index.html.erb
<div class="flex justify-end">
  <% items = [] %>
  <% items << { text: "New poi", link: new_admin_poi_path } %>
  <% items << { text: "New poi route", link: new_admin_poi_route_path } %>
  <%= render "shared/dropdown_menu", items: items %>
</div>

<div class="flex flex-col my-6">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Id</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"></th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"></th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <% @pois.each do |poi| %>
              <tr class="place-content-start align-top h-16">
                <td class="px-6 py-2 whitespace-nowrap w-1/12">
                  <div class="text-sm text-gray-500"><%= link_to poi.id, edit_admin_poi_path(poi) %></div>
                </td>
                <td class="px-6 py-2 whitespace-nowrap w-3/12">
                  <span class="text-sm text-gray-900 font-bold">
                    <%= link_to poi.name, edit_admin_poi_path(poi) %>
                  </span>
                </td>
                <td class="px-6 py-2 whitespace-nowrap w-2/12"></td>
                <td class="px-6 py-2 whitespace-nowrap w-6/12"></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<p><%= "#{@pois.count} results" %></p>

app/views/admin/pois/new.html.erb
<h1 class="my-3">New Poi</h1>

<div class="mt-10 sm:mt-0">
  <div class="md:grid md:grid-cols-4 md:gap-6">
    <div class="mt-5 md:mt-0 md:col-span-2">
      <%= form_with model: [:admin, @poi] do |form| %>
        <div class="shadow overflow-hidden sm:rounded-md">
          <div class="px-4 py-5 bg-white sm:p-6">
            <div class="grid grid-cols-6 gap-6">
              <%= render "form", form: form %>
            </div>
          </div>

          <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
            <button type="submit" class="btn">Save</button>
          </div>
        </div>
      <% end %>
    </div>

    <div class="md:col-span-2">
      <div class="px-4 sm:px-0"></div>
    </div>
  </div>
</div>