config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  scope "/:locale", locale: /#{I18n.available_locales.join('|')}/ do
    namespace :admin do 
      resources :areas, param: :slug do
        resources :problems, only: :index
      end
      resources :problems, except: :index
      resources :boulders
      resources :sectors
      resources :imports do
        get 'apply', on: :member
      end
      resources :topos
      resources :problem_imports
      resources :bleau_problems
      resources :lines
      resources :pois
      resources :poi_routes
      resources :contribution_requests
      resources :contributions
      resources :audits
      resources :redirects, only: :new

      get "contribute", to: "contribute#dashboard"

      root 'areas#index'
    end

    scope "articles" do
      scope "beginners-guide" do
        get '/', to: "articles#beginners_guide", as: :beginners_guide
        get 'equipment', to: "articles#equipment", as: :equipment
        get 'choose-area', to: "articles#choose_area", as: :choose_area
        get 'choose-problems', to: "articles#choose_problems", as: :choose_problems
        get 'climb-safely', to: "articles#climb_safely", as: :climb_safely
        get 'rules', to: "articles#rules", as: :rules
      end
      scope "top-areas" do
        get '/', to: redirect("/%{locale}/wicklow")
        get 'level', to: redirect("/%{locale}/wicklow"), as: :legacy_top_areas_level # keep until end of 2023
        get 'groups', to: redirect("/%{locale}/wicklow"), as: :legacy_top_areas_groups # keep until end of 2023
        get 'beginner', to: redirect("/%{locale}/articles/beginners-guide/choose-area"), as: :legacy_top_areas_beginner # keep until end of 2023
        get 'train', to: "articles#top_areas_train", as: :top_areas_train
        get 'dry_fast', to: "articles#top_areas_dry_fast", as: :top_areas_dry_fast
      end
      root to: redirect("/%{locale}/articles/beginners-guide"), as: :articles
    end

    resources :reports

    namespace :mapping do
      resources :problems, only: [:show, :index]
      resources :contributions, only: [:show, :new, :create]
      resources :requests, controller: "contribution_requests", only: [:index]
      get 'map(/:slug)', to: '/map#index', as: :map, defaults: { contribute: true }
      get "/", to: "areas#index"
    end
    get "contribute/map", to: redirect('/%{locale}/mapping/map'), as: :map_contribute_legacy_redirect # can be removed as soon as 2024-01-01

    scope 'wicklow' do
      resources :sectors, only: [:show, :index]
      resources :problems, only: [:index]

      get "/levels", to: "areas#levels", as: :areas_levels

      get "/areas", to: redirect("/%{locale}/wicklow"), as: :areas_legacy # keep until ??

      get ":slug/:id", to: "problems#show", as: :area_problem, id: /\d.*/
      get ":slug/map", to: redirect('/%{locale}/map/%{slug}'), as: :map_area_legacy_redirect # keep until end of 2023
      get ":slug/problems", to: "areas#problems", as: :area_problems
      get ":slug", to: "areas#show", as: :area

      get "/", to: "areas#index", as: :areas
    end

    get 'map(/:slug)', to: 'map#index', as: :map
    get 'app', to: 'pages#app', as: :app
    get 'privacy', to: 'pages#privacy', as: :privacy
    get 'about', to: 'pages#about', as: :about
    get 'contribute', to: 'pages#contribute', as: :contribute
    get 'sector7a', to: 'sector7a#index', as: :sector7a
    get 'sector7a/problems', to: 'sector7a#problems', as: :sector7a_problems
    get 'sector7a/map', to: 'map#index', as: :sector7a_map, defaults: { sector7a: true }

    resources :redirects, only: :new # useful for redirects where we only know the problem_id or area_id, eg. mapbox

    # Permalinks (don't remove!)
    get '/p/:id', to: "welcome#problem_permalink" # used by the apps to redirect to a problem webpage
  end

  namespace :api do
    namespace :v1 do
      resources :topos, only: :show
      resources :areas do
        resources :topos, only: :index
        get "map", to: "maps#show", as: :area_map
      end
    end
  end

  get "search", to: "search#search", as: :search
  get '/:locale', to: 'welcome#index', locale: /#{I18n.available_locales.join('|')}/, as: :root_localized
  root to: 'welcome#root'

  mount Sidekiq::Web => "/sidekiqq"

  # =============
  # Proxy routes 
  # =============
  # Use proxy mode (=streaming) instead of redirects to allow CDNs to easily cache our assets
  # inspired by https://edgeguides.rubyonrails.org/active_storage_overview.html#putting-a-cdn-in-front-of-active-storage
  # more info: https://github.com/rails/rails/tree/main/activestorage/app/controllers

  # Guessable urls (used by the mobile apps)
  get '/proxy/topos/:id', to: "proxy#show", as: :topo_proxy

  # General solution
  direct :cdn_image do |model, options|
    expires_in = options.delete(:expires_in) { ActiveStorage.urls_expire_in }
    options = options.merge(host: Rails.application.config.asset_host) unless Rails.env.local?

    if model.respond_to?(:signed_id)
      route_for(
        :rails_service_blob_proxy,
        model.signed_id(expires_in: expires_in),
        model.filename,
        options
      )
    else
      signed_blob_id = model.blob.signed_id(expires_in: expires_in)
      variation_key  = model.variation.key
      filename       = model.blob.filename

      route_for(
        :rails_blob_representation_proxy,
        signed_blob_id,
        variation_key,
        filename,
        options
      )
    end
  end
end

app/models/contribution_request.rb
class ContributionRequest < ApplicationRecord
  include Geolocatable
  geolocatable :location_estimated

  belongs_to :problem

  audited
  
  STATES = %w(open closed)
  scope :open, -> { where(state: "open") }
  scope :closed, -> { where(state: "closed") }

  validates :location_estimated, presence: true
  validates :state, inclusion: { in: STATES }
end

app/controllers/admin/contribution_requests_controller.rb
class Admin::ContributionRequestsController < Admin::BaseController
  def show
    contribution_request = ContributionRequest.find(params[:id])
    redirect_to edit_admin_contribution_request_path(contribution_request)
  end

  def new 
    @problem = Problem.find(params[:problem_id])

    @contribution_request = @problem.contribution_requests.build
  end

  def create
    @problem = Problem.find(params[:contribution_request][:problem_id])

    @contribution_request = ContributionRequest.new(what: "photo", state: "open")
    @contribution_request.assign_attributes(contribution_request_params)

    if @contribution_request.save
      flash[:notice] = "Contribution Request created"
      redirect_to [:admin, @contribution_request.problem]
    else
      flash[:error] = @contribution_request.errors.full_messages.join('; ')
      render "new", status: :unprocessable_entity
    end
  end

  def edit
    set_contribution_request
  end

  def update
    set_contribution_request

    @contribution_request.assign_attributes(contribution_request_params)

    if @contribution_request.save
      flash[:notice] = "Contribution request updated"
      redirect_to [:admin, @contribution_request.problem]
    else
      flash[:error] = @contribution_request.errors.full_messages.join('; ')
      render "edit", status: :unprocessable_entity
    end
  end

  private 
  def contribution_request_params
    params.require(:contribution_request).
      permit(:problem_id, :location_estimated_lat, :location_estimated_lon, :state, :comment)
  end

  def set_contribution_request
    @contribution_request = ContributionRequest.find(params[:id])
  end
end

app/controllers/mapping/contribution_requests_controller.rb
class Mapping::ContributionRequestsController < ApplicationController
  def index
    factory = RGeo::GeoJSON::EntityFactory.instance

    problem_features = ContributionRequest.open.where.not(location_estimated: nil).group_by(&:location_estimated).map do |location, requests|
      problems = requests.map(&:problem).sort_by{|p| p.ascents.to_i }.reverse
      problem = problems.first

      hash = {}.with_indifferent_access

      hash.merge!(problem.slice(:steepness, :featured, :popularity))

      group_name = problems.count > 1 ? "#{problem.name_debug} + #{problems.count - 1}" : problem.name_debug

      name_fr = I18n.with_locale(:fr) { group_name }
      name_en = I18n.with_locale(:en) { group_name }
      hash[:name] = name_fr
      hash[:name_en] = (name_en != name_fr) ? name_en : ""

      hash[:problems] = problems.map{|p| { name: p.name_debug, id: p.id, grade: p.grade } }

      hash.deep_transform_keys! { |key| key.camelize(:lower) }

      factory.feature(location, nil, hash)
    end

    feature_collection = factory.feature_collection(
      problem_features
    )

    respond_to do |format|
      format.geojson do
        render json: JSON.pretty_generate(RGeo::GeoJSON.encode(feature_collection))
      end
    end
  end
end

app/views/admin/contribution_requests/_form.html.erb
<div data-controller="coordinates" class="contents">
  <div class="col-span-6 sm:col-span-2">
    <%= form.label :location_estimated_lat, "Latitude estimated" %>
    <%= form.text_field :location_estimated_lat, value: @contribution_request.location_estimated&.lat, "data-action": "paste->coordinates#paste", "data-coordinates-target": "latitude" %>
  </div>
  <div class="col-span-6 sm:col-span-2">
    <%= form.label :location_estimated_lon, "Longitude estimated" %>
    <%= form.text_field :location_estimated_lon, value: @contribution_request.location_estimated&.lon, "data-action": "paste->coordinates#paste", "data-coordinates-target": "longitude" %>
  </div>
  
  <div class="col-span-6 sm:col-span-2 flex items-end mb-3">
    <%= link_to "copy", "javascript: void(0)", "data-action": "coordinates#copy", "data-coordinates-target": "link", class: "text-emerald-600 font-semibold" %>
  </div>
  
  <div class="col-span-6 sm:col-span-4 sm:col-start-1">
    <%= form.label :comment, "Comment (admin only)" %>
    <%= form.text_area :comment, rows: 5 %>
  </div>
  
  <% if @contribution_request.persisted? %>
    <div class="col-span-6 sm:col-span-2 sm:col-start-1">
      <%= form.label :state %>
      <%= form.select :state, ContributionRequest::STATES %>
    </div>
  <% end %>
</div>

app/views/admin/contribution_requests/edit.html.erb
<% problem = @contribution_request.problem %>

<% add_breadcrumb "Wicklow", admin_areas_path %>
<% add_breadcrumb problem.area.name, admin_area_problems_path(area_slug: problem.area.slug, sector_id: problem.sector&.id) %>
<% add_breadcrumb "Problem ##{problem.id}", admin_problem_path(problem) %>
<% add_breadcrumb "Contribution Request ##{@contribution_request.id}", nil, class: "active" %>

<div class="mt-10 sm:mt-0">
  <div class="md:grid md:grid-cols-6 md:gap-6">
    <div class="mt-5 md:mt-0 md:col-span-3">
      <%= form_with model: [:admin, @contribution_request] do |form| %>
        <div class="shadow overflow-hidden sm:rounded-md">
          <div class="px-4 py-5 bg-white sm:p-6">
            <div class="grid grid-cols-6 gap-6">
              <%= render "form", form: form %>
            </div>
          </div>
          <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
            <button type="submit" class="btn">Update</button>
          </div>
        </div>
      <% end %>
    </div>

    <div class="mt-5 md:mt-0 md:col-span-2 md:col-start-5">
      <div class="mb-8 shadow overflow-hidden sm:rounded-md">
        <div class="px-4 py-5 bg-white sm:p-6">
          <%= link_to mapping_map_path(pid: @contribution_request.problem.id), target: "_blank" do %>
            <div class="flex items-center space-x-2 text-emerald-600">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"/>
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"/>
              </svg>
              <div>See on contribute map</div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/contribution_requests/new.html.erb
<h1 class="my-3 text-3xl font-bold">New contribution request</h1>

<div class="mt-10">
  <div class="md:grid md:grid-cols-4 md:gap-6">
    <div class="mt-5 md:mt-0 md:col-span-2">
      <%= form_with model: [:admin, @contribution_request] do |form| %>
        <%= form.hidden_field :problem_id, value: @problem.id %>
        <div class="mb-4">
          <%= problem_circle_view_with_name(@problem) %>
        </div>
        <div class="shadow overflow-hidden sm:rounded-md">
          <div class="px-4 py-5 bg-white sm:p-6">
            <div class="grid grid-cols-6 gap-6">
              <%= render "form", form: form %>
            </div>
          </div>
          <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
            <button type="submit" class="btn">Create</button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>