config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  scope "/:locale", locale: /#{I18n.available_locales.join('|')}/ do
    namespace :admin do 
      resources :areas, param: :slug do
        resources :problems, only: :index
      end
      resources :problems, except: :index
      resources :boulders
      resources :sectors
      resources :imports do
        get 'apply', on: :member
      end
      resources :topos
      resources :problem_imports
      resources :bleau_problems
      resources :lines
      resources :pois
      resources :poi_routes
      resources :contribution_requests
      resources :contributions
      resources :audits
      resources :redirects, only: :new

      get "contribute", to: "contribute#dashboard"

      root 'areas#index'
    end

    scope "articles" do
      scope "beginners-guide" do
        get '/', to: "articles#beginners_guide", as: :beginners_guide
        get 'equipment', to: "articles#equipment", as: :equipment
        get 'choose-area', to: "articles#choose_area", as: :choose_area
        get 'choose-problems', to: "articles#choose_problems", as: :choose_problems
        get 'climb-safely', to: "articles#climb_safely", as: :climb_safely
        get 'rules', to: "articles#rules", as: :rules
      end
      scope "top-areas" do
        get '/', to: redirect("/%{locale}/wicklow")
        get 'level', to: redirect("/%{locale}/wicklow"), as: :legacy_top_areas_level # keep until end of 2023
        get 'groups', to: redirect("/%{locale}/wicklow"), as: :legacy_top_areas_groups # keep until end of 2023
        get 'beginner', to: redirect("/%{locale}/articles/beginners-guide/choose-area"), as: :legacy_top_areas_beginner # keep until end of 2023
        get 'train', to: "articles#top_areas_train", as: :top_areas_train
        get 'dry_fast', to: "articles#top_areas_dry_fast", as: :top_areas_dry_fast
      end
      root to: redirect("/%{locale}/articles/beginners-guide"), as: :articles
    end

    resources :reports

    namespace :mapping do
      resources :problems, only: [:show, :index]
      resources :contributions, only: [:show, :new, :create]
      resources :requests, controller: "contribution_requests", only: [:index]
      get 'map(/:slug)', to: '/map#index', as: :map, defaults: { contribute: true }
      get "/", to: "areas#index"
    end
    get "contribute/map", to: redirect('/%{locale}/mapping/map'), as: :map_contribute_legacy_redirect # can be removed as soon as 2024-01-01

    scope 'wicklow' do
      resources :sectors, only: [:show, :index]
      resources :problems, only: [:index]

      get "/levels", to: "areas#levels", as: :areas_levels

      get "/areas", to: redirect("/%{locale}/wicklow"), as: :areas_legacy # keep until ??

      get ":slug/:id", to: "problems#show", as: :area_problem, id: /\d.*/
      get ":slug/map", to: redirect('/%{locale}/map/%{slug}'), as: :map_area_legacy_redirect # keep until end of 2023
      get ":slug/problems", to: "areas#problems", as: :area_problems
      get ":slug", to: "areas#show", as: :area

      get "/", to: "areas#index", as: :areas
    end

    get 'map(/:slug)', to: 'map#index', as: :map
    get 'app', to: 'pages#app', as: :app
    get 'privacy', to: 'pages#privacy', as: :privacy
    get 'about', to: 'pages#about', as: :about
    get 'contribute', to: 'pages#contribute', as: :contribute
    get 'sector7a', to: 'sector7a#index', as: :sector7a
    get 'sector7a/problems', to: 'sector7a#problems', as: :sector7a_problems
    get 'sector7a/map', to: 'map#index', as: :sector7a_map, defaults: { sector7a: true }

    resources :redirects, only: :new # useful for redirects where we only know the problem_id or area_id, eg. mapbox

    # Permalinks (don't remove!)
    get '/p/:id', to: "welcome#problem_permalink" # used by the apps to redirect to a problem webpage
  end

  namespace :api do
    namespace :v1 do
      resources :topos, only: :show
      resources :areas do
        resources :topos, only: :index
        get "map", to: "maps#show", as: :area_map
      end
    end
  end

  get "search", to: "search#search", as: :search
  get '/:locale', to: 'welcome#index', locale: /#{I18n.available_locales.join('|')}/, as: :root_localized
  root to: 'welcome#root'

  mount Sidekiq::Web => "/sidekiqq"

  # =============
  # Proxy routes 
  # =============
  # Use proxy mode (=streaming) instead of redirects to allow CDNs to easily cache our assets
  # inspired by https://edgeguides.rubyonrails.org/active_storage_overview.html#putting-a-cdn-in-front-of-active-storage
  # more info: https://github.com/rails/rails/tree/main/activestorage/app/controllers

  # Guessable urls (used by the mobile apps)
  get '/proxy/topos/:id', to: "proxy#show", as: :topo_proxy

  # General solution
  direct :cdn_image do |model, options|
    expires_in = options.delete(:expires_in) { ActiveStorage.urls_expire_in }
    options = options.merge(host: Rails.application.config.asset_host) unless Rails.env.local?

    if model.respond_to?(:signed_id)
      route_for(
        :rails_service_blob_proxy,
        model.signed_id(expires_in: expires_in),
        model.filename,
        options
      )
    else
      signed_blob_id = model.blob.signed_id(expires_in: expires_in)
      variation_key  = model.variation.key
      filename       = model.blob.filename

      route_for(
        :rails_blob_representation_proxy,
        signed_blob_id,
        variation_key,
        filename,
        options
      )
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def new
    @contribution = Contribution.new(
      # TODO: make DRY
      contributor_name: session[:contribution_name],
      contributor_email: session[:contribution_email],
    )
  end

  def create
    @contribution = Contribution.new(contribution_params)

    # TODO: make DRY
    session[:contribution_name] = @contribution.contributor_name
    session[:contribution_email] = @contribution.contributor_email

    if @contribution.save
      flash[:notice] = t("views.reports.new.flash_success")

      ContributeMailer.with(contribution: @contribution).new_contribution_email.deliver_later

      redirect_to contribute_path
    else
      # flash[:error] = "Error"
      render "new", status: :unprocessable_entity
    end
  end

  def contribution_params
    params.require(:contribution).permit(
      :comment, :contributor_name, :contributor_email
    )
  end
end

app/views/reports/_form.html.erb
<% if @contribution.errors.any? %>
  <div class="rounded-md bg-red-50 p-4 my-4">
  <div class="flex">
    <div class="flex-shrink-0">
      <svg class="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z" clip-rule="evenodd" />
      </svg>
    </div>
    <div class="ml-3">
      <h3 class="text-sm font-medium text-red-800">Errors</h3>
      <div class="mt-2 text-sm text-red-700">
        <ul role="list" class="list-disc space-y-1 pl-5">
          <% @contribution.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<% end %>


<div class="space-y-10 divide-y divide-gray-900/10">

  <div class="grid grid-cols-1 gap-x-8 gap-y-8 md:grid-cols-3">
      <div class="px-4 sm:px-0">
        <h2 class="text-base font-semibold leading-7 text-gray-900"><%= t("views.reports.new.mistake") %></h2>
        <p class="mt-1 text-sm leading-6 text-gray-600"><%= t("views.reports.new.mistake_description") %></p>
      </div>

      <div class="bg-white shadow-sm ring-1 ring-gray-900/5 sm:rounded-xl md:col-span-2">
        <div class="px-4 py-6 sm:p-8">
          <div class="grid max-w-2xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
            <div class="col-span-full">
              <div class="mt-2">
                <%= form.text_area :comment, rows: 10, class:"block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-emerald-600 sm:text-sm sm:leading-6" %>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>

  <div class="grid grid-cols-1 gap-x-8 gap-y-8 pt-10 md:grid-cols-3">
      <div class="px-4 sm:px-0">
        <div class="text-base font-semibold leading-7 text-gray-400 flex items-center space-x-2">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21" />
          </svg>
          <span><%= t("views.mapping.contributions.new.private") %></span>
        </div>

        <h2 class="text-base font-semibold leading-7 text-gray-900"><%= t("views.mapping.contributions.new.private_info") %></h2>
        
        <p class="mt-1 text-sm leading-6 text-gray-600">
          <%= t("views.mapping.contributions.new.private_info_description") %>
        </p>
      </div>

      <div class="bg-white shadow-sm ring-1 ring-gray-900/5 sm:rounded-xl md:col-span-2">
        <div class="px-4 py-6 sm:p-8">
          <div class="grid max-w-2xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">

            <div class="sm:col-span-2 sm:col-start-1">
              <%= form.label :contributor_name, class: "block text-sm font-medium leading-6 text-gray-900" %>
              <div class="mt-2">
                <%= form.text_field :contributor_name, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-emerald-600 sm:text-sm sm:leading-6" %>
              </div>
            </div>

            <div class="sm:col-span-4 sm:col-start-1">
              <%= form.label :contributor_email, class: "block text-sm font-medium leading-6 text-gray-900" %>
              <div class="mt-2">
                <%= form.text_field :contributor_email, type: "email", autocomplete: "email", class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-emerald-600 sm:text-sm sm:leading-6" %>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
</div>

<div class="px-4 sm:px-0 mx-auto mt-12 flex items-center justify-end gap-x-6">
  <%= form.submit t("views.mapping.contributions.new.submit"), class: "flex w-full sm:w-64 justify-center rounded-md bg-emerald-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-emerald-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-600" %>
</div>

app/views/reports/new.html.erb
<% set_meta_tags title: t("views.reports.new.metas.title") %>

<div class="max-w-7xl mx-auto pt-6 sm:px-6 lg:px-8">
  <div class="px-4 sm:px-0">
    <%= link_to contribute_path, class: "hover:text-gray-700" do %>
      <div class="flex items-center space-x-2 text-sm font-medium text-gray-500">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
        </svg>
        <span><%= t("views.breadcrumbs.back") %></span>
      </div>
    <% end %>
  </div>
</div>

<div class="max-w-7xl mx-auto sm:px-6 lg:px-8 pb-8">
  <div class="md:grid md:grid-cols-2 md:gap-16 mb-4">
    <div class="">
      <h1 class="text-3xl font-bold mb-4 mt-2 px-4 sm:px-0"><%= t("views.reports.new.title") %></h1>
    </div>
  </div>

  <div class="mt-8">
    <%= form_with model: @contribution, url: reports_path do |form| %>
      <%# = form.hidden_field :problem_id %>
      <%= render "form", form: form %>
    <% end %>
  </div>
</div>