config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  scope "/:locale", locale: /#{I18n.available_locales.join('|')}/ do
    namespace :admin do 
      resources :areas, param: :slug do
        resources :problems, only: :index
      end
      resources :problems, except: :index
      resources :boulders
      resources :sectors
      resources :imports do
        get 'apply', on: :member
      end
      resources :topos
      resources :problem_imports
      resources :bleau_problems
      resources :lines
      resources :pois
      resources :poi_routes
      resources :contribution_requests
      resources :contributions
      resources :audits
      resources :redirects, only: :new

      get "contribute", to: "contribute#dashboard"

      root 'areas#index'
    end

    scope "articles" do
      scope "beginners-guide" do
        get '/', to: "articles#beginners_guide", as: :beginners_guide
        get 'equipment', to: "articles#equipment", as: :equipment
        get 'choose-area', to: "articles#choose_area", as: :choose_area
        get 'choose-problems', to: "articles#choose_problems", as: :choose_problems
        get 'climb-safely', to: "articles#climb_safely", as: :climb_safely
        get 'rules', to: "articles#rules", as: :rules
      end
      scope "top-areas" do
        get '/', to: redirect("/%{locale}/wicklow")
        get 'level', to: redirect("/%{locale}/wicklow"), as: :legacy_top_areas_level # keep until end of 2023
        get 'groups', to: redirect("/%{locale}/wicklow"), as: :legacy_top_areas_groups # keep until end of 2023
        get 'beginner', to: redirect("/%{locale}/articles/beginners-guide/choose-area"), as: :legacy_top_areas_beginner # keep until end of 2023
        get 'train', to: "articles#top_areas_train", as: :top_areas_train
        get 'dry_fast', to: "articles#top_areas_dry_fast", as: :top_areas_dry_fast
      end
      root to: redirect("/%{locale}/articles/beginners-guide"), as: :articles
    end

    resources :reports

    namespace :mapping do
      resources :problems, only: [:show, :index]
      resources :contributions, only: [:show, :new, :create]
      resources :requests, controller: "contribution_requests", only: [:index]
      get 'map(/:slug)', to: '/map#index', as: :map, defaults: { contribute: true }
      get "/", to: "areas#index"
    end
    get "contribute/map", to: redirect('/%{locale}/mapping/map'), as: :map_contribute_legacy_redirect # can be removed as soon as 2024-01-01

    scope 'wicklow' do
      resources :sectors, only: [:show, :index]
      resources :problems, only: [:index]

      get "/levels", to: "areas#levels", as: :areas_levels

      get "/areas", to: redirect("/%{locale}/wicklow"), as: :areas_legacy # keep until ??

      get ":slug/:id", to: "problems#show", as: :area_problem, id: /\d.*/
      get ":slug/map", to: redirect('/%{locale}/map/%{slug}'), as: :map_area_legacy_redirect # keep until end of 2023
      get ":slug/problems", to: "areas#problems", as: :area_problems
      get ":slug", to: "areas#show", as: :area

      get "/", to: "areas#index", as: :areas
    end

    get 'map(/:slug)', to: 'map#index', as: :map
    get 'app', to: 'pages#app', as: :app
    get 'privacy', to: 'pages#privacy', as: :privacy
    get 'about', to: 'pages#about', as: :about
    get 'contribute', to: 'pages#contribute', as: :contribute
    get 'sector7a', to: 'sector7a#index', as: :sector7a
    get 'sector7a/problems', to: 'sector7a#problems', as: :sector7a_problems
    get 'sector7a/map', to: 'map#index', as: :sector7a_map, defaults: { sector7a: true }

    resources :redirects, only: :new # useful for redirects where we only know the problem_id or area_id, eg. mapbox

    # Permalinks (don't remove!)
    get '/p/:id', to: "welcome#problem_permalink" # used by the apps to redirect to a problem webpage
  end

  namespace :api do
    namespace :v1 do
      resources :topos, only: :show
      resources :areas do
        resources :topos, only: :index
        get "map", to: "maps#show", as: :area_map
      end
    end
  end

  get "search", to: "search#search", as: :search
  get '/:locale', to: 'welcome#index', locale: /#{I18n.available_locales.join('|')}/, as: :root_localized
  root to: 'welcome#root'

  mount Sidekiq::Web => "/sidekiqq"

  # =============
  # Proxy routes 
  # =============
  # Use proxy mode (=streaming) instead of redirects to allow CDNs to easily cache our assets
  # inspired by https://edgeguides.rubyonrails.org/active_storage_overview.html#putting-a-cdn-in-front-of-active-storage
  # more info: https://github.com/rails/rails/tree/main/activestorage/app/controllers

  # Guessable urls (used by the mobile apps)
  get '/proxy/topos/:id', to: "proxy#show", as: :topo_proxy

  # General solution
  direct :cdn_image do |model, options|
    expires_in = options.delete(:expires_in) { ActiveStorage.urls_expire_in }
    options = options.merge(host: Rails.application.config.asset_host) unless Rails.env.local?

    if model.respond_to?(:signed_id)
      route_for(
        :rails_service_blob_proxy,
        model.signed_id(expires_in: expires_in),
        model.filename,
        options
      )
    else
      signed_blob_id = model.blob.signed_id(expires_in: expires_in)
      variation_key  = model.variation.key
      filename       = model.blob.filename

      route_for(
        :rails_blob_representation_proxy,
        signed_blob_id,
        variation_key,
        filename,
        options
      )
    end
  end
end

app/controllers/api/v1/maps_controller.rb
class Api::V1::MapsController < ActionController::Base
  include ProblemsHelper

  def show
    area = Area.find(params[:area_id])

    factory = RGeo::GeoJSON::EntityFactory.instance

    problem_features = Problem.with_location.where(area_id: area.id).map do |problem|
      hash = {}.with_indifferent_access
      hash[:name] = problem.name_debug
      hash[:problem_id] = problem.id
      hash[:updated_at] = problem.updated_at
      hash.deep_transform_keys! { |key| key.camelize(:lower) }

      # simple-style attributes to make the map look nicer on geojson.io
      # https://github.com/mapbox/simplestyle-spec/tree/master/1.1.0
      # Important: keep the key exactly as it it (don't camelize it)
      hash[:"marker-color"] = uicolor(problem.sector&.color, fallback: "#ccc")

      factory.feature(problem.location, nil, hash)
    end

    boulder_features = Boulder.where(area_id: area.id).map do |boulder|
      hash = {}.with_indifferent_access
      hash[:boulder_id] = boulder.id
      hash[:updated_at] = boulder.updated_at
      hash.deep_transform_keys! { |key| key.camelize(:lower) }

      factory.feature(boulder.polygon, nil, hash)
    end

    feature_collection = factory.feature_collection(
      problem_features + boulder_features
    )

    json = JSON.pretty_generate(RGeo::GeoJSON.encode(feature_collection))

    respond_to do |format|
      format.geojson do
        if params[:download].present?
          send_data json, filename: "area-#{area.id}-#{area.slug}.geojson", type: 'application/geo+json'
        else
          render json: json
        end 
      end
    end
  end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  layout "map"

  def index
    if params[:slug] && (area = Area.find_by(slug: params[:slug]))
      @area = area # FIXME: don't forget to refactor _map_nav when changing this
      @bounds = { 
        south_west_lat: area.bounds[:south_west].lat,
        south_west_lon: area.bounds[:south_west].lon,
        north_east_lat: area.bounds[:north_east].lat,
        north_east_lon: area.bounds[:north_east].lon,
      }.
      with_indifferent_access.deep_transform_keys { |key| key.camelize(:lower) }
    end

    if params[:pid] && (problem = Problem.find(params[:pid]))
      location = if params[:contribute]
        problem.contribution_requests.first&.location_estimated
      else
        problem.location
      end
      
      return unless location.present?
      
      @problem = { 
        id: problem.id, # FIXME: don't forget to refactor _map_nav when changing this
        lat: location.lat,
        lon: location.lon,
        name: I18n.with_locale(:fr) { problem.name_with_fallback },
        name_en: I18n.with_locale(:en) { problem.name_with_fallback },
        grade: problem.grade,
      }.
      with_indifferent_access.deep_transform_keys { |key| key.camelize(:lower) }
    end
  end
end

app/views/map/_filters.html.erb
<div data-controller="reveal">
  <div class="absolute inset-x-0 bottom-0 z-10 pb-8 text-center">
    <button data-action="reveal#show" type="button" class="inline-flex items-center rounded-lg border border-gray-300 bg-white px-4 py-2 text-base font-normal text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:ring-offset-2">
      <span data-mapbox-target="filterCounter" class="hidden inline-flex justify-center items-center mr-2 w-4 h-4 text-xs font-semibold text-emerald-800 bg-emerald-300 rounded-full">
          1
      </span>
      <svg data-mapbox-target="filterIcon" xmlns="http://www.w3.org/2000/svg" class="-ml-1 mr-2 h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.5">
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4" />
      </svg>
      <span><%= t('views.map.filters.label') %></span>
  </button>
  </div>
  
  <div data-reveal-target="item" class="relative z-20 hidden" role="dialog">
    <%= render 'filters_modal' %>
  </div>  
</div>

app/views/map/_filters_modal.html.erb
<!--
  Background backdrop, show/hide based on modal state.

  Entering: "ease-out duration-300"
    From: "opacity-0"
    To: "opacity-100"
  Leaving: "ease-in duration-200"
    From: "opacity-100"
    To: "opacity-0"
-->
<div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"></div>

<div class="fixed inset-0 z-20 overflow-y-auto">
  <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
    <!--
      Modal panel, show/hide based on modal state.

      Entering: "ease-out duration-300"
        From: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
        To: "opacity-100 translate-y-0 sm:scale-100"
      Leaving: "ease-in duration-200"
        From: "opacity-100 translate-y-0 sm:scale-100"
        To: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
    -->
    <div class="relative transform overflow-hidden rounded-lg bg-white px-4 pt-5 pb-4 text-left shadow-xl transition-all sm:my-8 w-full sm:max-w-lg sm:p-6">
      <div class="absolute top-0 right-0 pt-4 pr-4">
        <button data-action="reveal#hide" type="button" class="rounded-md bg-white text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:ring-offset-2">
          <span class="sr-only">Close</span>
          <!-- Heroicon name: outline/x-mark -->
          <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="">
        <div class="mt-3 text-center sm:mt-0">
          <h3 class="text-lg font-medium leading-6 text-gray-900 mb-4"><%= t('views.map.filters.level') %></h3>
        </div>

          <fieldset class="">
            <legend class="sr-only">Levels</legend>
            <div class="relative -space-y-px rounded-md bg-white">
              <!-- Checked: "bg-emerald-50 border-emerald-200 z-20", Not Checked: "border-gray-200" -->
              <label class="rounded-tl-md rounded-tr-md relative border p-4 flex cursor-pointer md:pl-4 md:pr-6 grid grid-cols-2 focus:outline-none">
                <span class="flex items-center text-sm">
                  <input data-action="mapbox#didSelectFilter" data-mapbox-target="gradeRadioButton" type="radio" name="gradeRadioButton" value="beginner" class="h-4 w-4 text-emerald-600 border-gray-300 focus:ring-emerald-500">
                  <!-- Checked: "text-emerald-900", Not Checked: "text-gray-900" -->
                  <span class="ml-3 font-medium"><%= t('views.map.filters.beginner') %></span>
                </span>
                
                <!-- Checked: "text-emerald-700", Not Checked: "text-gray-500" -->
                <span class="ml-6 pl-1 text-sm md:ml-0 md:pl-0 text-right text-gray-400"><%= t('views.map.filters.beginner_label') %></span>
              </label>

              <% (4..7).each do |level| %>

                <!-- Checked: "bg-emerald-50 border-emerald-200 z-20", Not Checked: "border-gray-200" -->
                <label class="relative border p-4 flex cursor-pointer md:pl-4 md:pr-6 grid grid-cols-2 focus:outline-none">
                  <span class="flex items-center text-sm">
                    <input data-action="mapbox#didSelectFilter" data-mapbox-target="gradeRadioButton" type="radio" name="gradeRadioButton" value="<%= "level#{level}" %>" class="h-4 w-4 text-emerald-600 border-gray-300 focus:ring-emerald-500">
                    <!-- Checked: "text-emerald-900", Not Checked: "text-gray-900" -->
                    <span class="ml-3 font-medium"><%= t("views.map.filters.level#{level}") %></span>
                  </span>
                  
                  <!-- Checked: "text-emerald-700", Not Checked: "text-gray-500" -->
                  <span class="ml-6 pl-1 text-sm md:ml-0 md:pl-0 text-right text-gray-400"></span>
                </label>

              <% end %>

              <!-- Checked: "bg-emerald-50 border-emerald-200 z-20", Not Checked: "border-gray-200" -->
              <label class="rounded-bl-md rounded-br-md relative border p-4 flex cursor-pointer md:pl-4 md:pr-6 grid grid-cols-2 focus:outline-none">
                <span class="flex items-center text-sm">
                  <input data-action="mapbox#didSelectFilter" data-mapbox-target="gradeRadioButton" type="radio" name="gradeRadioButton" value="custom" class="h-4 w-4 text-emerald-600 border-gray-300 focus:ring-emerald-500">
                  <!-- Checked: "text-emerald-900", Not Checked: "text-gray-900" -->
                  <span class="ml-3 font-medium"><%= t('views.map.filters.custom') %></span>
                </span>
                
                <!-- Checked: "text-emerald-700", Not Checked: "text-gray-500" -->
                <span class="ml-6 pl-1 text-sm md:ml-0 md:pl-0 text-right text-gray-400"></span>
              </label>
            </div>
          </fieldset>

          <div data-mapbox-target="customGradePicker" class="hidden grid grid-cols-2 gap-8 my-4">
            <div class="">
              <label for="gradeMin" class="block text-sm font-medium text-gray-700"><%= t('views.map.filters.grade_min') %></label>
              <select data-mapbox-target="gradeMin" data-action="mapbox#didSelectGradeMin" id="gradeMin" name="gradeMin" class="mt-1 block w-full rounded-md border-gray-300 py-2 pl-3 pr-10 text-base focus:border-emerald-500 focus:outline-none focus:ring-emerald-500 sm:text-sm">
                <option>1a</option>
                <option>1b</option>
                <option>1c</option>
                <option>2a</option>
                <option>2b</option>
                <option>2c</option>
                <option>3a</option>
                <option>3b</option>
                <option>3c</option>
                <option selected>4a</option>
                <option>4b</option>
                <option>4c</option>
                <option>5a</option>
                <option>5b</option>
                <option>5c</option>
                <option>6a</option>
                <option>6b</option>
                <option>6c</option>
                <option>7a</option>
                <option>7b</option>
                <option>7c</option>
                <option>8a</option>
                <option>8b</option>
                <option>8c</option>
                <option>9a</option>
              </select>
            </div>

            <div>
              <label for="gradeMax" class="block text-sm font-medium text-gray-700"><%= t('views.map.filters.grade_max') %></label>
              <select data-mapbox-target="gradeMax" data-action="mapbox#didSelectGradeMax" id="gradeMax" name="gradeMax" class="mt-1 block w-full rounded-md border-gray-300 py-2 pl-3 pr-10 text-base focus:border-emerald-500 focus:outline-none focus:ring-emerald-500 sm:text-sm">
                <option>1a</option>
                <option>1b</option>
                <option>1c</option>
                <option>2a</option>
                <option>2b</option>
                <option>2c</option>
                <option>3a</option>
                <option>3b</option>
                <option>3c</option>
                <option>4a</option>
                <option>4b</option>
                <option>4c</option>
                <option selected>5a</option>
                <option>5b</option>
                <option>5c</option>
                <option>6a</option>
                <option>6b</option>
                <option>6c</option>
                <option>7a</option>
                <option>7b</option>
                <option>7c</option>
                <option>8a</option>
                <option>8b</option>
                <option>8c</option>
                <option>9a</option>
              </select>
            </div>
          </div>

      </div>
      <div class="mt-5 sm:mt-4 sm:flex sm:flex-row-reverse">
        <button data-action="reveal#hide mapbox#applyFilters" type="button" class="inline-flex w-full justify-center rounded-md border border-transparent bg-emerald-600 px-4 py-2 text-base font-medium text-white shadow-sm hover:bg-emerald-700 focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:ring-offset-2 sm:ml-3 sm:w-auto sm:text-sm"><%= t('views.map.filters.apply') %></button>
        <button data-action="reveal#hide mapbox#clearFilters" type="button" class="mt-3 inline-flex w-full justify-center rounded-md border border-gray-300 bg-white px-4 py-2 text-base font-medium text-gray-700 shadow-sm hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:mt-0 sm:w-auto sm:text-sm"><%= t('views.map.filters.clear') %></button>
      </div>
    </div>
  </div>
</div>

app/views/map/index.html.erb
<% if params[:contribute] %> 
  <% set_meta_tags nofollow: true %>
  <% set_meta_tags title: t("views.mapping.map.metas.title") %>
  <% set_meta_tags description: t("views.mapping.map.metas.description") %>
<% elsif @area %> 
  <% set_meta_tags title: t("views.map.area.metas.title", area: @area.name) %>
  <% set_meta_tags description: t("views.map.area.metas.description", area: @area.name) %>

  <% if @area.cover.persisted? %>
  <% set_meta_tags og: { type: "website", image: cdn_image_url(@area.cover.variant(:medium)) } %>
  <% end %>
  <% set_meta_tags canonical: map_url(@area) %>
<% else %>
  <% set_meta_tags title: t("views.map.wicklow.metas.title") %>
  <% set_meta_tags description: t("views.map.wicklow.metas.description") %>
  <% set_meta_tags og: { type: "website", image: image_url("map-og.png") } %>
  <% set_meta_tags canonical: map_url %>
<% end %>

<div 
data-controller="mapbox"
data-action="gotoproblem@window->mapbox#gotoproblem gotoarea@window->mapbox#gotoarea"
class="flex-auto relative"
id='map'
data-mapbox-target="map"
data-mapbox-locale-value="<%= I18n.locale %>"

data-mapbox-contribute-source-value="<%= mapping_requests_path(format: :geojson) %>"
data-mapbox-contribute-value="<%= params[:contribute] ? "true" : "false" %>"


<% if @problem %> 
data-mapbox-problem-value="<%= @problem.to_json %>" 
<% end %>

<% if @bounds %> 
data-mapbox-bounds-value="<%= @bounds.to_json %>"
<% end %>

data-mapbox-token-value="<%= Rails.env.local? ? ENV['MAPBOX_DEV_ACCESS_KEY'] : Rails.application.credentials.dig(:mapbox, :access_token) %>"
>
  <%= render "filters" %>

</div>